// Code generated by api/rpc/internal/gen from gridwell/v1/data.proto. DO NOT EDIT.
//
// The proto is the one description of these records. Change a field
// there and run `buf generate` (make proto-check does it for you);
// editing this file by hand is undone by the next regeneration.

package rpc

import pb "github.com/josephburnett/gridwell/api/gen/gridwell/v1"

// Tile is the persistent unit of content in a grid. kind selects which
// subset of the optional fields is meaningful; the DDL CHECK constraint
// enforces it.
type Tile struct {
	ID      string `json:"id,omitempty"`
	Version int64  `json:"version,omitempty"`
	GridID  string `json:"grid_id,omitempty"`
	Kind    string `json:"kind,omitempty"`
	X       int64  `json:"x,omitempty"`
	Y       int64  `json:"y,omitempty"`
	W       int64  `json:"w,omitempty"`
	H       int64  `json:"h,omitempty"`
	// well-only: the child grid's framing, which is at once the preview
	// frame, the descent target, and the ascent return value. One shape: a
	// float center in the child grid's coordinates (view_cx, view_cy) plus
	// the pane-size-independent intrinsic zoom (live over overtake), the same
	// three numbers a root grid keeps on its own row. view_zoom == 0 means
	// never visited.
	ViewZoom    float64 `json:"view_zoom,omitempty"`
	ViewCx      float64 `json:"view_cx,omitempty"`
	ViewCy      float64 `json:"view_cy,omitempty"`
	ChildGridID string  `json:"child_grid_id,omitempty"`
	// text-only: text_x/text_y is the scroll offset; text_w/text_h is the
	// window size; all four are doc-space px. text_mode is "rendered" or
	// "text". blob_id points at the markdown source in the blobs table.
	TextX    int64  `json:"text_x,omitempty"`
	TextY    int64  `json:"text_y,omitempty"`
	TextW    int64  `json:"text_w,omitempty"`
	TextH    int64  `json:"text_h,omitempty"`
	TextMode string `json:"text_mode,omitempty"`
	BlobID   int64  `json:"blob_id,omitempty"`
	// url-only: the http(s) URL plus a pointer at the last-frozen JPEG
	// preview (in the blobs table; hash-deduped across clones).
	URLString     string `json:"url_string,omitempty"`
	PreviewBlobID int64  `json:"preview_blob_id,omitempty"`
	// alt_text is the canonical display label, rendered verbatim by the
	// client. Stamped at insert time (for plugin-owned tiles, the entry name;
	// for an exit well, the mounted plugin's label).
	AltText string `json:"alt_text,omitempty"`
	// reference reports that this well is a link, not owned content: its
	// child_grid_id is a qualified cross-plugin reference rather than a bare
	// local child grid. It is the single authoritative "is a link" signal.
	// The client renders a dashed border from it, and delete and clone treat
	// a qualified child_grid_id as unlink-only and share, never cascade. Set
	// by the server in qualifyTiles, from a child that arrived already
	// qualified, so render and the store cannot disagree on what a link is.
	// Wire-only, derived, never a stored column.
	Reference bool `json:"reference,omitempty"`
	// content_zoom scales the content rendered inside a text, shell, or url
	// tile: the text font, the terminal font, the page zoom. It is framing,
	// not content — persisted per tile, and it never bumps version. 0 means
	// unset and renders at 1.0. Written by the SetTile content_zoom arm
	// only.
	ContentZoom float64 `json:"content_zoom,omitempty"`
	// url_history is a url tile's persisted navigation back-stack, JSON
	// {index, entries:[{url,title}]} and capped, captured at freeze so a
	// revived tile can still go back. Rides the url SetTile writeback. An
	// empty value on a write leaves the stored history untouched, so a
	// partial capture cannot clobber it, mirroring the preview-JPEG rule.
	URLHistory string `json:"url_history,omitempty"`
	// link_target_id makes a leaf tile (text, url, shell, pane) a link: a
	// qualified "<plugin-uuid>/<tile-id>" reference to the tile that owns the
	// content. The link row stores no content of its own — no blob, no url,
	// no preview — and readers resolve bytes, preview, and session through
	// the target id, which the router routes anywhere, including through
	// transit chains that prepend one hop segment exactly as they do for a
	// well's qualified child_grid_id. Kind stays the target's kind;
	// link-ness is orthogonal metadata. A well's link variant is a qualified
	// child_grid_id instead, and reference is the single derived "is a link"
	// bit over both shapes. Deleting a link only unlinks.
	LinkTargetID string `json:"link_target_id,omitempty"`
	// url_frozen is the user's standing freeze on a url tile: set by the
	// explicit freeze gesture, cleared by the reconnect button. While set,
	// descending does not auto-go-live, unlike the transient navigate-away
	// freeze, which auto-revives on return. Framing-class: written by the
	// SetTile url_frozen arm only, and it never bumps version.
	URLFrozen bool `json:"url_frozen,omitempty"`
	// serves_page: the owning plugin serves this tile's content as web
	// content through the /content/ door, over the ServeContent RPC — an
	// image file, an HTML page. The client gives the descent url-tile
	// semantics (a live native view on a desktop host, open-in-new-tab on a
	// browser host) at the derived address
	// /content/<content-token>/<tile-id>/, built at render time from the
	// current origin and never persisted, because ports are ephemeral.
	// Plugin-declared, derived from the content itself, such as the
	// filename's media type in fs. Never a stored column.
	ServesPage bool `json:"serves_page,omitempty"`
	// text_presentation is the owning plugin's declaration of how a text
	// tile's body presents: "plain" (monospace, no markdown interpretation —
	// source code, logs), "rendered" (document renderer only), or "both"
	// (rendered by default, and the user may toggle to the raw source). ""
	// means no declaration, and the stored user text_mode rules, which is the
	// case for the home's own documents. Plugin-derived from the content
	// itself, such as the filename or a sniff in fs. Wire-only, never a
	// stored column.
	TextPresentation string `json:"text_presentation,omitempty"`
	// status_detail is the owning plugin's current trouble with this tile,
	// for the client to display verbatim. A connection well whose last dial
	// failed carries that error until the connection comes up, so the failure
	// surfaces instead of presenting as a tile that is merely waiting.
	// Wire-only, derived. Never a stored column, never set by clients.
	StatusDetail string `json:"status_detail,omitempty"`
}

// Grid is the persistent unit of canvas. Tiles live in grids; wells
// point at child grids. The root grid has no parent.
type Grid struct {
	ID      string `json:"id,omitempty"`
	Version int64  `json:"version,omitempty"`
	// writable reports whether the grid's owning plugin accepts mutations.
	// It is per grid, not per namespace, because one connection fronts many
	// remote plugins with differing capabilities. Stamped by the serving node
	// from the owning plugin's Info at a leaf, passed through verbatim in
	// transit. Wire-only, never persisted.
	Writable bool `json:"writable,omitempty"`
	// scratch_grid_id is the owning plugin's ephemeral-url scratch grid,
	// qualified from the receiver's perspective and chained through mounts,
	// by the same stamping rule as writable. "" when the plugin has none.
	// Wire-only.
	ScratchGridID string `json:"scratch_grid_id,omitempty"`
	// stale marks a grid the source could not answer for: this is the
	// remembered answer, not the live one. Two node-side stampers share the
	// one meaning — internal/sourcecache on its serve-stale path, and a
	// plugin adapter answering a dark source from the rows it minted.
	// Wire-only, never persisted. The cache also obeys it: an answer already
	// stamped stale is never remembered.
	Stale bool `json:"stale,omitempty"`
	// node_ns is the namespace chain of the node serving this grid, from the
	// receiver's perspective: "" for a grid served by the node you are
	// talking to, "<transit>/<conn>" or deeper through mounts, each transit
	// hop prepending its segment exactly like scratch_grid_id. It is the one
	// owner of "which node is this pane inside": the client keys its per-pane
	// + menu context by it and routes Handshake with it. Wire-only, never
	// persisted.
	NodeNS string `json:"node_ns,omitempty"`
	// menu_entries is the owning plugin's declared (+) menu additions for
	// this grid. Stamped from Info by the serving node, and verbatim through
	// transit with grid_id prefixed per hop. Wire-only.
	MenuEntries []MenuEntry `json:"menu_entries,omitempty"`
	// host_content says this grid PROJECTS host state — a directory, the
	// process table — instead of holding content of its own: read-only rows
	// the client renders with the host treatment (the outside tint, the exit
	// border family). Declared by the owning plugin (plugin.v1
	// InfoResponse.host_content), stamped onto the grid by the adapter that
	// serves it, and carried verbatim through transit like writable. It is
	// what a reader consults instead of learning a kind's name; it replaced
	// source_kind.
	// Wire-only, never persisted.
	HostContent bool `json:"host_content,omitempty"`
	// glyph is the owning plugin's declared identity glyph for this grid, from
	// the same vocabulary as InfoResponse.glyph ("" = no declaration, and the
	// client falls back to the well face or the mount door's glyph). It
	// travels on the GRID because a plugin-list lookup cannot answer for a
	// grid reached through a mount. Stamped by the adapter, verbatim in
	// transit. Wire-only, never persisted.
	Glyph string `json:"glyph,omitempty"`
}

// MenuEntry is one plugin-declared (+) menu entry: an extra plugin root,
// such as the trashcan. Declared in Info, stamped per grid by the serving
// node exactly like writable, and passed verbatim through transit hops,
// where grid_id gains the hop prefix like every id. The swatch behaves like
// a plugin swatch over grid_id: click descends, drag drops an exit-well
// link.
//
// 5 and 6 were kind and param_schema, the creation-entry half. No client
// could ever receive one.
type MenuEntry struct {
	ID     string `json:"id,omitempty"`
	Label  string `json:"label,omitempty"`
	Glyph  string `json:"glyph,omitempty"`
	Color  string `json:"color,omitempty"`
	GridID string `json:"grid_id,omitempty"`
}

// PluginInfo mirrors gridwell/v1/data.proto's PluginInfo.
type PluginInfo struct {
	UUID       string `json:"uuid,omitempty"`
	Kind       string `json:"kind,omitempty"`
	Label      string `json:"label,omitempty"`
	Writable   bool   `json:"writable,omitempty"`
	RootGridID string `json:"root_grid_id,omitempty"`
	// grid; click-enter descends here
	ScratchGridID string `json:"scratch_grid_id,omitempty"`
	// scratch grid for ephemeral url tiles; "" if none
	// root_view_cx/cy/zoom is the plugin root grid's last-saved viewport,
	// forwarded verbatim from InfoResponse. Zero means never visited; the
	// client substitutes the default calibrated zoom on enterPlugin.
	RootViewCx   float64 `json:"root_view_cx,omitempty"`
	RootViewCy   float64 `json:"root_view_cy,omitempty"`
	RootViewZoom float64 `json:"root_view_zoom,omitempty"`
	// info_error is set when the plugin's Info handshake failed or timed out,
	// distinguishing broken from healthy but rootless, which otherwise
	// present identically as root_grid_id == "". Empty when Info succeeded,
	// whether or not it declared a root.
	InfoError string `json:"info_error,omitempty"`
	// glyph mirrors InfoResponse.glyph for the client's plugin faces: the
	// menu swatch and the drag ghost. "" is the generic globe.
	Glyph string `json:"glyph,omitempty"`
	// menu_entries mirrors InfoResponse.menu_entries with grid targets
	// qualified for the receiver: root entries join the plugin's row in the
	// (+) menu.
	MenuEntries []MenuEntry `json:"menu_entries,omitempty"`
}

// ConnectionInfo is one of the node's connections as the handshake lists
// it: a row in the + menu that descends into the remote node's home. uuid
// is "<node id>/<connection name>", the namespace every reference through
// the connection carries.
type ConnectionInfo struct {
	UUID         string  `json:"uuid,omitempty"`
	Label        string  `json:"label,omitempty"`
	RootGridID   string  `json:"root_grid_id,omitempty"`
	RootViewCx   float64 `json:"root_view_cx,omitempty"`
	RootViewCy   float64 `json:"root_view_cy,omitempty"`
	RootViewZoom float64 `json:"root_view_zoom,omitempty"`
	StatusDetail string  `json:"status_detail,omitempty"`
}

// SearchResult mirrors gridwell/v1/data.proto's SearchResult.
type SearchResult struct {
	Tile    Tile    `json:"tile,omitempty"`
	Path    []Tile  `json:"path,omitempty"`
	Snippet string  `json:"snippet,omitempty"`
	Score   float64 `json:"score,omitempty"`
}

// GetGridResponse mirrors gridwell/v1/data.proto's GetGridResponse.
type GetGridResponse struct {
	Grid  Grid   `json:"grid,omitempty"`
	Tiles []Tile `json:"tiles,omitempty"`
}

// CloneTileRequest mirrors gridwell/v1/data.proto's CloneTileRequest.
type CloneTileRequest struct {
	// insert, so no cycle can form and no client-supplied
	// location is needed
	TileID string `json:"tile_id,omitempty"`
	// layout carries no claim
	DestGridID string `json:"dest_grid_id,omitempty"`
	X          int64  `json:"x,omitempty"`
	Y          int64  `json:"y,omitempty"`
}

// PlaceTile is the single placement writeback: placement is one fact,
// (grid_id, x, y, w, h), and one verb owns it. grid_id is the destination
// grid, the same as the tile's current grid for a pure resize. The server
// refuses overlap, and refuses placing a well inside its own subtree by
// walking ancestors from grid_id — a server-derived check, with no
// client-supplied path. Placement never crosses a plugin boundary; there is
// no cross-plugin move, only link or clone.
type PlaceTileRequest struct {
	TileID string `json:"tile_id,omitempty"`
	// claim. Overlap is still refused server-side, in the same
	// transaction.
	GridID string `json:"grid_id,omitempty"`
	X      int64  `json:"x,omitempty"`
	Y      int64  `json:"y,omitempty"`
	W      int64  `json:"w,omitempty"`
	H      int64  `json:"h,omitempty"`
}

// DeleteTileRequest mirrors gridwell/v1/data.proto's DeleteTileRequest.
type DeleteTileRequest struct {
	TileID string `json:"tile_id,omitempty"`
}

// ShellSessionAlive reports whether the tile's Gridwell-private tmux
// session currently exists. Called on shell descent so the client can
// decide whether to show the refresh button:
//   - alive=true             → button shown; refresh attaches.
//   - alive=false, no snap   → button shown; refresh creates fresh.
//   - alive=false, snap set  → button hidden; the JPEG is all that
//     remains (the session died, can't bring it back).
type ShellSessionAliveRequest struct {
	TileID string `json:"tile_id,omitempty"`
}

// ShellSessionAliveResponse mirrors gridwell/v1/data.proto's ShellSessionAliveResponse.
type ShellSessionAliveResponse struct {
	Alive bool `json:"alive,omitempty"`
}

// GridChanged mirrors gridwell/v1/data.proto's GridChanged.
type GridChanged struct {
	GridID string `json:"grid_id,omitempty"`
}

// TileChanged mirrors gridwell/v1/data.proto's TileChanged.
type TileChanged struct {
	Tile Tile `json:"tile,omitempty"`
}

// TileRemoved mirrors gridwell/v1/data.proto's TileRemoved.
type TileRemoved struct {
	GridID string `json:"grid_id,omitempty"`
	TileID string `json:"tile_id,omitempty"`
}

// EventPluginHealth reports a transition in a plugin's event-stream health,
// as seen by the router's fan-in (fanInEvents and watchPlugin in
// internal/server/router.go). Emitted on the down transition (healthy=false,
// detail carrying the dial, recv, or Info error that caused it) and again on
// recovery (healthy=true, detail=""). Only on a change of state, never per
// retry attempt, so a flapping plugin does not spam the client.
type PluginHealth struct {
	PluginUUID string `json:"plugin_uuid,omitempty"`
	Healthy    bool   `json:"healthy,omitempty"`
	Detail     string `json:"detail,omitempty"`
}

// TileToProto converts a Tile to its wire form.
func TileToProto(v *Tile) *pb.Tile {
	if v == nil {
		return nil
	}
	return &pb.Tile{
		Id:               v.ID,
		Version:          v.Version,
		GridId:           v.GridID,
		Kind:             v.Kind,
		X:                v.X,
		Y:                v.Y,
		W:                v.W,
		H:                v.H,
		ViewZoom:         v.ViewZoom,
		ViewCx:           v.ViewCx,
		ViewCy:           v.ViewCy,
		ChildGridId:      v.ChildGridID,
		TextX:            v.TextX,
		TextY:            v.TextY,
		TextW:            v.TextW,
		TextH:            v.TextH,
		TextMode:         v.TextMode,
		BlobId:           v.BlobID,
		UrlString:        v.URLString,
		PreviewBlobId:    v.PreviewBlobID,
		AltText:          v.AltText,
		Reference:        v.Reference,
		ContentZoom:      v.ContentZoom,
		UrlHistory:       v.URLHistory,
		LinkTargetId:     v.LinkTargetID,
		UrlFrozen:        v.URLFrozen,
		ServesPage:       v.ServesPage,
		TextPresentation: v.TextPresentation,
		StatusDetail:     v.StatusDetail,
	}
}

// TilesToProto converts a slice of Tile to wire form.
func TilesToProto(vs []Tile) []*pb.Tile {
	if vs == nil {
		return nil
	}
	out := make([]*pb.Tile, len(vs))
	for i := range vs {
		out[i] = TileToProto(&vs[i])
	}
	return out
}

// TileFromProto converts a wire Tile back.
func TileFromProto(p *pb.Tile) *Tile {
	if p == nil {
		return nil
	}
	out := &Tile{
		ID:               p.Id,
		Version:          p.Version,
		GridID:           p.GridId,
		Kind:             p.Kind,
		X:                p.X,
		Y:                p.Y,
		W:                p.W,
		H:                p.H,
		ViewZoom:         p.ViewZoom,
		ViewCx:           p.ViewCx,
		ViewCy:           p.ViewCy,
		ChildGridID:      p.ChildGridId,
		TextX:            p.TextX,
		TextY:            p.TextY,
		TextW:            p.TextW,
		TextH:            p.TextH,
		TextMode:         p.TextMode,
		BlobID:           p.BlobId,
		URLString:        p.UrlString,
		PreviewBlobID:    p.PreviewBlobId,
		AltText:          p.AltText,
		Reference:        p.Reference,
		ContentZoom:      p.ContentZoom,
		URLHistory:       p.UrlHistory,
		LinkTargetID:     p.LinkTargetId,
		URLFrozen:        p.UrlFrozen,
		ServesPage:       p.ServesPage,
		TextPresentation: p.TextPresentation,
		StatusDetail:     p.StatusDetail,
	}
	return out
}

// TilesFromProto converts a slice of wire Tile back.
func TilesFromProto(ps []*pb.Tile) []Tile {
	if ps == nil {
		return nil
	}
	out := make([]Tile, len(ps))
	for i, p := range ps {
		if v := TileFromProto(p); v != nil {
			out[i] = *v
		}
	}
	return out
}

// GridToProto converts a Grid to its wire form.
func GridToProto(v *Grid) *pb.Grid {
	if v == nil {
		return nil
	}
	return &pb.Grid{
		Id:            v.ID,
		Version:       v.Version,
		Writable:      v.Writable,
		ScratchGridId: v.ScratchGridID,
		Stale:         v.Stale,
		NodeNs:        v.NodeNS,
		MenuEntries:   MenuEntriesToProto(v.MenuEntries),
		HostContent:   v.HostContent,
		Glyph:         v.Glyph,
	}
}

// GridFromProto converts a wire Grid back.
func GridFromProto(p *pb.Grid) *Grid {
	if p == nil {
		return nil
	}
	out := &Grid{
		ID:            p.Id,
		Version:       p.Version,
		Writable:      p.Writable,
		ScratchGridID: p.ScratchGridId,
		Stale:         p.Stale,
		NodeNS:        p.NodeNs,
		MenuEntries:   MenuEntriesFromProto(p.MenuEntries),
		HostContent:   p.HostContent,
		Glyph:         p.Glyph,
	}
	return out
}

// MenuEntryToProto converts a MenuEntry to its wire form.
func MenuEntryToProto(v *MenuEntry) *pb.MenuEntry {
	if v == nil {
		return nil
	}
	return &pb.MenuEntry{
		Id:     v.ID,
		Label:  v.Label,
		Glyph:  v.Glyph,
		Color:  v.Color,
		GridId: v.GridID,
	}
}

// MenuEntriesToProto converts a slice of MenuEntry to wire form.
func MenuEntriesToProto(vs []MenuEntry) []*pb.MenuEntry {
	if vs == nil {
		return nil
	}
	out := make([]*pb.MenuEntry, len(vs))
	for i := range vs {
		out[i] = MenuEntryToProto(&vs[i])
	}
	return out
}

// MenuEntryFromProto converts a wire MenuEntry back.
func MenuEntryFromProto(p *pb.MenuEntry) *MenuEntry {
	if p == nil {
		return nil
	}
	out := &MenuEntry{
		ID:     p.Id,
		Label:  p.Label,
		Glyph:  p.Glyph,
		Color:  p.Color,
		GridID: p.GridId,
	}
	return out
}

// MenuEntriesFromProto converts a slice of wire MenuEntry back.
func MenuEntriesFromProto(ps []*pb.MenuEntry) []MenuEntry {
	if ps == nil {
		return nil
	}
	out := make([]MenuEntry, len(ps))
	for i, p := range ps {
		if v := MenuEntryFromProto(p); v != nil {
			out[i] = *v
		}
	}
	return out
}

// PluginInfoToProto converts a PluginInfo to its wire form.
func PluginInfoToProto(v *PluginInfo) *pb.PluginInfo {
	if v == nil {
		return nil
	}
	return &pb.PluginInfo{
		Uuid:          v.UUID,
		Kind:          v.Kind,
		Label:         v.Label,
		Writable:      v.Writable,
		RootGridId:    v.RootGridID,
		ScratchGridId: v.ScratchGridID,
		RootViewCx:    v.RootViewCx,
		RootViewCy:    v.RootViewCy,
		RootViewZoom:  v.RootViewZoom,
		InfoError:     v.InfoError,
		Glyph:         v.Glyph,
		MenuEntries:   MenuEntriesToProto(v.MenuEntries),
	}
}

// PluginInfosToProto converts a slice of PluginInfo to wire form.
func PluginInfosToProto(vs []PluginInfo) []*pb.PluginInfo {
	if vs == nil {
		return nil
	}
	out := make([]*pb.PluginInfo, len(vs))
	for i := range vs {
		out[i] = PluginInfoToProto(&vs[i])
	}
	return out
}

// PluginInfoFromProto converts a wire PluginInfo back.
func PluginInfoFromProto(p *pb.PluginInfo) *PluginInfo {
	if p == nil {
		return nil
	}
	out := &PluginInfo{
		UUID:          p.Uuid,
		Kind:          p.Kind,
		Label:         p.Label,
		Writable:      p.Writable,
		RootGridID:    p.RootGridId,
		ScratchGridID: p.ScratchGridId,
		RootViewCx:    p.RootViewCx,
		RootViewCy:    p.RootViewCy,
		RootViewZoom:  p.RootViewZoom,
		InfoError:     p.InfoError,
		Glyph:         p.Glyph,
		MenuEntries:   MenuEntriesFromProto(p.MenuEntries),
	}
	return out
}

// PluginInfosFromProto converts a slice of wire PluginInfo back.
func PluginInfosFromProto(ps []*pb.PluginInfo) []PluginInfo {
	if ps == nil {
		return nil
	}
	out := make([]PluginInfo, len(ps))
	for i, p := range ps {
		if v := PluginInfoFromProto(p); v != nil {
			out[i] = *v
		}
	}
	return out
}

// ConnectionInfoToProto converts a ConnectionInfo to its wire form.
func ConnectionInfoToProto(v *ConnectionInfo) *pb.ConnectionInfo {
	if v == nil {
		return nil
	}
	return &pb.ConnectionInfo{
		Uuid:         v.UUID,
		Label:        v.Label,
		RootGridId:   v.RootGridID,
		RootViewCx:   v.RootViewCx,
		RootViewCy:   v.RootViewCy,
		RootViewZoom: v.RootViewZoom,
		StatusDetail: v.StatusDetail,
	}
}

// ConnectionInfosToProto converts a slice of ConnectionInfo to wire form.
func ConnectionInfosToProto(vs []ConnectionInfo) []*pb.ConnectionInfo {
	if vs == nil {
		return nil
	}
	out := make([]*pb.ConnectionInfo, len(vs))
	for i := range vs {
		out[i] = ConnectionInfoToProto(&vs[i])
	}
	return out
}

// ConnectionInfoFromProto converts a wire ConnectionInfo back.
func ConnectionInfoFromProto(p *pb.ConnectionInfo) *ConnectionInfo {
	if p == nil {
		return nil
	}
	out := &ConnectionInfo{
		UUID:         p.Uuid,
		Label:        p.Label,
		RootGridID:   p.RootGridId,
		RootViewCx:   p.RootViewCx,
		RootViewCy:   p.RootViewCy,
		RootViewZoom: p.RootViewZoom,
		StatusDetail: p.StatusDetail,
	}
	return out
}

// ConnectionInfosFromProto converts a slice of wire ConnectionInfo back.
func ConnectionInfosFromProto(ps []*pb.ConnectionInfo) []ConnectionInfo {
	if ps == nil {
		return nil
	}
	out := make([]ConnectionInfo, len(ps))
	for i, p := range ps {
		if v := ConnectionInfoFromProto(p); v != nil {
			out[i] = *v
		}
	}
	return out
}

// SearchResultToProto converts a SearchResult to its wire form.
func SearchResultToProto(v *SearchResult) *pb.SearchResult {
	if v == nil {
		return nil
	}
	return &pb.SearchResult{
		Tile:    TileToProto(&v.Tile),
		Path:    TilesToProto(v.Path),
		Snippet: v.Snippet,
		Score:   v.Score,
	}
}

// SearchResultsToProto converts a slice of SearchResult to wire form.
func SearchResultsToProto(vs []SearchResult) []*pb.SearchResult {
	if vs == nil {
		return nil
	}
	out := make([]*pb.SearchResult, len(vs))
	for i := range vs {
		out[i] = SearchResultToProto(&vs[i])
	}
	return out
}

// SearchResultFromProto converts a wire SearchResult back.
func SearchResultFromProto(p *pb.SearchResult) *SearchResult {
	if p == nil {
		return nil
	}
	out := &SearchResult{
		Path:    TilesFromProto(p.Path),
		Snippet: p.Snippet,
		Score:   p.Score,
	}
	if v := TileFromProto(p.Tile); v != nil {
		out.Tile = *v
	}
	return out
}

// SearchResultsFromProto converts a slice of wire SearchResult back.
func SearchResultsFromProto(ps []*pb.SearchResult) []SearchResult {
	if ps == nil {
		return nil
	}
	out := make([]SearchResult, len(ps))
	for i, p := range ps {
		if v := SearchResultFromProto(p); v != nil {
			out[i] = *v
		}
	}
	return out
}

// GetGridResponseToProto converts a GetGridResponse to its wire form.
func GetGridResponseToProto(v *GetGridResponse) *pb.GetGridResponse {
	if v == nil {
		return nil
	}
	return &pb.GetGridResponse{
		Grid:  GridToProto(&v.Grid),
		Tiles: TilesToProto(v.Tiles),
	}
}

// GetGridResponseFromProto converts a wire GetGridResponse back.
func GetGridResponseFromProto(p *pb.GetGridResponse) *GetGridResponse {
	if p == nil {
		return nil
	}
	out := &GetGridResponse{
		Tiles: TilesFromProto(p.Tiles),
	}
	if v := GridFromProto(p.Grid); v != nil {
		out.Grid = *v
	}
	return out
}

// CloneTileRequestToProto converts a CloneTileRequest to its wire form.
func CloneTileRequestToProto(v *CloneTileRequest) *pb.CloneTileRequest {
	if v == nil {
		return nil
	}
	return &pb.CloneTileRequest{
		TileId:     v.TileID,
		DestGridId: v.DestGridID,
		X:          v.X,
		Y:          v.Y,
	}
}

// CloneTileRequestFromProto converts a wire CloneTileRequest back.
func CloneTileRequestFromProto(p *pb.CloneTileRequest) *CloneTileRequest {
	if p == nil {
		return nil
	}
	out := &CloneTileRequest{
		TileID:     p.TileId,
		DestGridID: p.DestGridId,
		X:          p.X,
		Y:          p.Y,
	}
	return out
}

// PlaceTileRequestToProto converts a PlaceTileRequest to its wire form.
func PlaceTileRequestToProto(v *PlaceTileRequest) *pb.PlaceTileRequest {
	if v == nil {
		return nil
	}
	return &pb.PlaceTileRequest{
		TileId: v.TileID,
		GridId: v.GridID,
		X:      v.X,
		Y:      v.Y,
		W:      v.W,
		H:      v.H,
	}
}

// PlaceTileRequestFromProto converts a wire PlaceTileRequest back.
func PlaceTileRequestFromProto(p *pb.PlaceTileRequest) *PlaceTileRequest {
	if p == nil {
		return nil
	}
	out := &PlaceTileRequest{
		TileID: p.TileId,
		GridID: p.GridId,
		X:      p.X,
		Y:      p.Y,
		W:      p.W,
		H:      p.H,
	}
	return out
}

// DeleteTileRequestToProto converts a DeleteTileRequest to its wire form.
func DeleteTileRequestToProto(v *DeleteTileRequest) *pb.DeleteTileRequest {
	if v == nil {
		return nil
	}
	return &pb.DeleteTileRequest{
		TileId: v.TileID,
	}
}

// DeleteTileRequestFromProto converts a wire DeleteTileRequest back.
func DeleteTileRequestFromProto(p *pb.DeleteTileRequest) *DeleteTileRequest {
	if p == nil {
		return nil
	}
	out := &DeleteTileRequest{
		TileID: p.TileId,
	}
	return out
}

// ShellSessionAliveRequestToProto converts a ShellSessionAliveRequest to its wire form.
func ShellSessionAliveRequestToProto(v *ShellSessionAliveRequest) *pb.ShellSessionAliveRequest {
	if v == nil {
		return nil
	}
	return &pb.ShellSessionAliveRequest{
		TileId: v.TileID,
	}
}

// ShellSessionAliveResponseFromProto converts a wire ShellSessionAliveResponse back.
func ShellSessionAliveResponseFromProto(p *pb.ShellSessionAliveResponse) *ShellSessionAliveResponse {
	if p == nil {
		return nil
	}
	out := &ShellSessionAliveResponse{
		Alive: p.Alive,
	}
	return out
}

// GridChangedToProto converts a GridChanged to its wire form.
func GridChangedToProto(v *GridChanged) *pb.GridChanged {
	if v == nil {
		return nil
	}
	return &pb.GridChanged{
		GridId: v.GridID,
	}
}

// GridChangedFromProto converts a wire GridChanged back.
func GridChangedFromProto(p *pb.GridChanged) *GridChanged {
	if p == nil {
		return nil
	}
	out := &GridChanged{
		GridID: p.GridId,
	}
	return out
}

// TileChangedToProto converts a TileChanged to its wire form.
func TileChangedToProto(v *TileChanged) *pb.TileChanged {
	if v == nil {
		return nil
	}
	return &pb.TileChanged{
		Tile: TileToProto(&v.Tile),
	}
}

// TileChangedFromProto converts a wire TileChanged back.
func TileChangedFromProto(p *pb.TileChanged) *TileChanged {
	if p == nil {
		return nil
	}
	out := &TileChanged{}
	if v := TileFromProto(p.Tile); v != nil {
		out.Tile = *v
	}
	return out
}

// TileRemovedToProto converts a TileRemoved to its wire form.
func TileRemovedToProto(v *TileRemoved) *pb.TileRemoved {
	if v == nil {
		return nil
	}
	return &pb.TileRemoved{
		GridId: v.GridID,
		TileId: v.TileID,
	}
}

// TileRemovedFromProto converts a wire TileRemoved back.
func TileRemovedFromProto(p *pb.TileRemoved) *TileRemoved {
	if p == nil {
		return nil
	}
	out := &TileRemoved{
		GridID: p.GridId,
		TileID: p.TileId,
	}
	return out
}

// PluginHealthToProto converts a PluginHealth to its wire form.
func PluginHealthToProto(v *PluginHealth) *pb.EventPluginHealth {
	if v == nil {
		return nil
	}
	return &pb.EventPluginHealth{
		PluginUuid: v.PluginUUID,
		Healthy:    v.Healthy,
		Detail:     v.Detail,
	}
}

// PluginHealthFromProto converts a wire EventPluginHealth back.
func PluginHealthFromProto(p *pb.EventPluginHealth) *PluginHealth {
	if p == nil {
		return nil
	}
	out := &PluginHealth{
		PluginUUID: p.PluginUuid,
		Healthy:    p.Healthy,
		Detail:     p.Detail,
	}
	return out
}
